(() => {
  const body=document.body,toggle=document.getElementById('experienceSwitch');
  const saved=localStorage.getItem('pa-experience');
  if(saved==='culture'||saved==='systems'){body.dataset.experience=saved;[...(toggle?.children||[])].forEach((el,i)=>el.classList.toggle('is-active',(saved==='systems'&&i===0)||(saved==='culture'&&i===1)))}
  toggle?.addEventListener('click',()=>setTimeout(()=>localStorage.setItem('pa-experience',body.dataset.experience||'systems'),0));

  const lab=document.getElementById('codeLab'),input=document.getElementById('codeLabInput'),frame=document.getElementById('codeLabFrame'),title=document.getElementById('codeLabTitle'),lessonTitle=document.getElementById('codeLabLessonTitle'),lesson=document.getElementById('codeLabLesson'),challenge=document.getElementById('codeLabChallenge'),status=document.getElementById('codeLabStatus');
  let current='html';
  const extra={
    python:{title:'Practica Python',lesson:'Tu primer script',text:'Python prioriza legibilidad. Esta demo valida y representa una salida segura en el navegador.',challenge:'Reto: crea una variable edad y úsala en print().',code:'nombre = "Pedro"\nedad = 20\nprint(f"Hola, {nombre}. Tengo {edad} años.")'},
    sql:{title:'Practica SQL',lesson:'Consulta tus datos',text:'SQL sirve para preguntar a una base de datos. Aquí simulamos una tabla de proyectos.',challenge:'Reto: cambia el filtro a published.',code:"SELECT name, status\nFROM projects\nWHERE status = 'development'\nORDER BY name;"},
    git:{title:'Simula Git',lesson:'Versiona sin miedo',text:'Visualiza un flujo Git sin tocar un repositorio real.',challenge:'Reto: asegúrate de incluir add, commit y push.',code:'git status\ngit add .\ngit commit -m "mi primer cambio"\ngit push'},
    docker:{title:'Simula Docker',lesson:'Contenedores en orden',text:'Representamos construcción y arranque sin ejecutar Docker en el navegador.',challenge:'Reto: añade docker compose down al inicio.',code:'docker compose build\ndocker compose up'},
    etl:{title:'Simula ETL',lesson:'Datos que sí sirven',text:'Diseña un pipeline de extracción, transformación y carga.',challenge:'Reto: incluye EXTRACT, TRANSFORM y LOAD.',code:'EXTRACT ventas.csv\nTRANSFORM limpiar_nulos, normalizar_fechas\nLOAD analytics.ventas'}
  };
  const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const simulate=()=>{if(!frame||!input)return;if(current==='python'){frame.srcdoc=`<style>body{font:15px ui-monospace;background:#111;color:#eee;padding:20px;white-space:pre-wrap}</style>Python demo ✓\n\n${esc(input.value)}`}else if(current==='sql'){frame.srcdoc=`<style>body{font:14px system-ui;padding:18px}table{border-collapse:collapse;width:100%}td,th{border:1px solid #bbb;padding:8px}</style><b>Consulta simulada</b><p>${esc(input.value)}</p><table><tr><th>name</th><th>status</th></tr><tr><td>Academic OS</td><td>development</td></tr><tr><td>Paso & Tradición</td><td>development</td></tr></table>`}else{frame.srcdoc=`<style>body{font:14px ui-monospace;background:#101114;color:#eee;padding:18px}.step{padding:9px;margin:7px 0;border:1px solid #333;border-radius:8px}</style><b>${current.toUpperCase()} · simulación</b>${input.value.split('\n').filter(Boolean).map((l,i)=>`<div class=step>✓ ${i+1}. ${esc(l)}</div>`).join('')}`};status.textContent='Ejecutado ✓'};
  document.addEventListener('click',e=>{const btn=e.target.closest('.practice-launch');if(!btn||!extra[btn.dataset.lab])return;e.preventDefault();e.stopImmediatePropagation();current=btn.dataset.lab;const d=extra[current];title.textContent=d.title;lessonTitle.textContent=d.lesson;lesson.textContent=d.text;challenge.textContent=d.challenge;input.value=d.code;lab.classList.add('is-open');lab.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';simulate()},true);
  document.getElementById('runCodeLab')?.addEventListener('click',()=>{if(extra[current])simulate()},true);
  document.getElementById('publishPractice')?.addEventListener('click',()=>{const drafts=JSON.parse(localStorage.getItem('pa-community-drafts')||'[]');drafts.unshift({id:Date.now(),alias:'Visitante',technology:(title.textContent||'Práctica').replace('Practica ','').replace('Simula ',''),code:input.value,created_at:new Date().toISOString(),reactions:{heart:0,fire:0,clap:0}});localStorage.setItem('pa-community-drafts',JSON.stringify(drafts.slice(0,30)));const b=document.getElementById('publishPractice');b.textContent='Guardada en Comunidad ✓';setTimeout(()=>b.textContent='Publicar práctica',1500)});
})();

(() => {
 const palette=document.getElementById('commandPalette'),input=document.getElementById('commandInput'),results=document.getElementById('commandResults');if(!palette||!input||!results)return;
 const commands=[['Inicio','Volver al hero',()=>location.href='#inicio'],['Sobre mí','Conoce a Pedro',()=>location.href='#about'],['Tecnologías','Explora y practica',()=>location.href='#skills'],['Proyectos','Ver trabajo',()=>location.href='#projects'],['Publicaciones','Leer novedades',()=>location.href='#publications'],['Certificados','Formación continua',()=>location.href='#certificates'],['Instagram','Red principal',()=>open('https://www.instagram.com/pedroagapito.pe','_blank')],['LinkedIn','Perfil profesional',()=>open('https://www.linkedin.com/in/pedro-jaramillo-rojas-agapito','_blank')]];
 const close=()=>palette.classList.remove('is-open');const render=()=>{const q=input.value.toLowerCase();results.innerHTML='';commands.filter(c=>(c[0]+' '+c[1]).toLowerCase().includes(q)).forEach(c=>{const b=document.createElement('button');b.className='command-item';b.innerHTML=`<span>${c[0]}</span><small>${c[1]}</small>`;b.onclick=()=>{close();c[2]()};results.appendChild(b)})};const openP=()=>{palette.classList.add('is-open');input.value='';render();setTimeout(()=>input.focus(),30)};
 document.getElementById('commandTrigger')?.addEventListener('click',openP);input.addEventListener('input',render);palette.querySelectorAll('[data-command-close]').forEach(x=>x.addEventListener('click',close));addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openP()}if(e.key==='Escape')close()});
})();
