(() => {
  'use strict';
  const cfg=window.PEDRO_SUPABASE;
  if(!cfg||!window.supabase?.createClient){alert('No se pudo cargar Supabase. Revisa tu conexión.');return;}
  const db=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  const $=id=>document.getElementById(id), loginView=$('loginView'),dashboardView=$('dashboardView'),loginForm=$('loginForm'),loginMessage=$('loginMessage'),logoutButton=$('logoutButton'),tabButtons=[...document.querySelectorAll('.tab-button[data-tab]')],itemsList=$('itemsList'),itemsEmpty=$('itemsEmpty'),newItemButton=$('newItemButton'),sectionEyebrow=$('sectionEyebrow'),sectionTitle=$('sectionTitle'),editorPlaceholder=$('editorPlaceholder'),editorPanel=$('editorPanel'),editorMessage=$('editorMessage'),moderationStats=$('moderationStats');
  const forms={posts:$('postForm'),projects:$('projectForm'),certificates:$('certificateForm'),technologies:$('technologyForm')};
  const labels={posts:['PUBLICACIONES','Novedades y artículos'],projects:['PROYECTOS','Proyectos del portafolio'],certificates:['CERTIFICADOS','Formación y credenciales'],technologies:['TECNOLOGÍAS','Tecnologías y herramientas'],community:['COMUNIDAD','Moderación de prácticas'],reports:['REPORTES','Incidencias de la Comunidad'],banned:['MODERACIÓN','Palabras prohibidas'],comments:['COMENTARIOS','Moderación de comentarios'],reviews:['RESEÑAS','Testimonios del portafolio']};
  let currentTab='posts',currentItems=[],selectedId=null,currentUser=null;
  const qs=(form,name)=>form?.elements.namedItem(name),esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;'),msg=(el,text='',type='')=>{if(!el)return;el.textContent=text;el.classList.remove('error','success');if(type)el.classList.add(type)},slugify=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')||`item-${Date.now()}`;
  async function verifyAdmin(user){if(!user?.id)return false;const {data,error}=await db.from('admin_users').select('user_id,active').eq('user_id',user.id).eq('active',true).maybeSingle();return !error&&Boolean(data)}
  function showLogin(){loginView.classList.remove('hidden');dashboardView.classList.add('hidden')}
  async function showDashboard(user){currentUser=user;loginView.classList.add('hidden');dashboardView.classList.remove('hidden');await switchTab(currentTab)}
  loginForm.addEventListener('submit',async e=>{e.preventDefault();msg(loginMessage,'Ingresando…');const email=$('loginEmail').value.trim(),password=$('loginPassword').value;const {data,error}=await db.auth.signInWithPassword({email,password});if(error)return msg(loginMessage,error.message,'error');if(!await verifyAdmin(data.user)){await db.auth.signOut();return msg(loginMessage,'Este usuario no tiene permisos de administrador.','error')}msg(loginMessage,'');await showDashboard(data.user)});
  logoutButton.addEventListener('click',async()=>{await db.auth.signOut();showLogin()});
  tabButtons.forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
  async function initAuth(){const {data:{user}}=await db.auth.getUser();if(user&&await verifyAdmin(user))await showDashboard(user);else showLogin()}
  async function switchTab(tab){currentTab=tab;selectedId=null;tabButtons.forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));sectionEyebrow.textContent=labels[tab][0];sectionTitle.textContent=labels[tab][1];newItemButton.classList.toggle('hidden',['reports','community','comments','reviews'].includes(tab));newItemButton.textContent=tab==='banned'?'+ Nueva palabra':tab==='technologies'?'+ Nueva tecnología':'+ Nuevo';hideForms();await loadItems()}
  async function loadItems(){msg(editorMessage,'');moderationStats.classList.add('hidden');let q;if(currentTab==='posts')q=db.from('posts').select('*').order('created_at',{ascending:false});else if(currentTab==='projects')q=db.from('projects').select('*').order('display_order',{ascending:true});else if(currentTab==='certificates')q=db.from('certificates').select('*').order('display_order',{ascending:true});else if(currentTab==='technologies')q=db.from('technologies').select('*').order('display_order',{ascending:true});else if(currentTab==='community')q=db.from('community_posts').select('*').order('created_at',{ascending:false});else if(currentTab==='reports')q=db.from('community_reports').select('*,community_posts(title,nickname,technology,code,status)').order('created_at',{ascending:false});else if(currentTab==='banned')q=db.from('banned_words').select('*').order('active',{ascending:false}).order('term',{ascending:true});else if(currentTab==='reviews')q=db.from('portfolio_reviews').select('*').order('created_at',{ascending:false});else if(currentTab==='comments'){const [pc,pr]=await Promise.all([db.from('community_comments').select('id,user_id,post_id,body,created_at,deleted_at,moderation_reason').order('created_at',{ascending:false}).limit(100),db.from('community_project_comments').select('id,user_id,project_id,body,created_at,deleted_at,moderation_reason').order('created_at',{ascending:false}).limit(100)]);if(pc.error||pr.error){itemsList.innerHTML='';itemsEmpty.classList.remove('hidden');itemsEmpty.textContent=`Error: ${(pc.error||pr.error)?.message||'No se pudieron cargar comentarios.'}`;return}const all=[...(pc.data||[]).map(x=>({...x,kind:'post'})),...(pr.data||[]).map(x=>({...x,kind:'project'}))].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));currentItems=all;renderItems();return;}else return;
    const {data,error}=await q;if(error){itemsList.innerHTML='';itemsEmpty.classList.remove('hidden');itemsEmpty.textContent=`Error: ${error.message}`;return}currentItems=data||[];if(currentTab==='community')await renderModerationStats();renderItems()}
  async function renderModerationStats(){const [p,r,b,t]=await Promise.all([db.from('community_posts').select('id',{count:'exact',head:true}).eq('status','pending'),db.from('community_reports').select('id',{count:'exact',head:true}).eq('status','pending'),db.from('banned_words').select('id',{count:'exact',head:true}).eq('active',true),db.from('technologies').select('id',{count:'exact',head:true}).eq('status','published')]);moderationStats.classList.remove('hidden');moderationStats.innerHTML=`<span><strong>${p.count||0}</strong> pendientes</span><span><strong>${r.count||0}</strong> reportes</span><span><strong>${b.count||0}</strong> palabras activas</span><span><strong>${t.count||0}</strong> tecnologías</span>`}
  function renderItems(){itemsEmpty.classList.toggle('hidden',currentItems.length>0);itemsEmpty.textContent=currentTab==='community'?'No hay publicaciones para moderar.':currentTab==='reports'?'No hay reportes.':currentTab==='banned'?'No hay palabras configuradas.':currentTab==='reviews'?'No hay reseñas todavía.':currentTab==='comments'?'No hay comentarios para moderar.':currentTab==='technologies'?'No hay tecnologías configuradas.':'Todavía no hay elementos.';itemsList.innerHTML=currentItems.map(i=>{if(currentTab==='community')return `<button class="item-row${selectedId===i.id?' active':''}" type="button" data-id="${esc(i.id)}"><strong>${esc(i.title||'Sin título')}</strong><span>@${esc(i.nickname||'Usuario')} · ${esc(i.technology||'')}</span><span class="status-pill status-${esc(i.status)}">${esc(i.status)}</span></button>`;if(currentTab==='reports')return `<button class="item-row${selectedId===i.id?' active':''}" type="button" data-id="${esc(i.id)}"><strong>${esc(i.community_posts?.title||'Publicación eliminada')}</strong><span>${esc(i.reason)} · ${esc(i.status)}</span></button>`;if(currentTab==='comments')return `<button class="item-row${selectedId===i.id?' active':''}" type="button" data-id="${esc(i.id)}"><strong>💬 ${esc((i.body||'').slice(0,70))}</strong><span>${i.kind==='project'?'Proyecto':'Publicación'} · ${esc(new Date(i.created_at).toLocaleString('es-PE'))}${i.deleted_at?' · RETIRADO':''}</span></button>`;if(currentTab==='banned')return `<button class="item-row${selectedId===i.id?' active':''}" type="button" data-id="${esc(i.id)}"><strong>${esc(i.term)}</strong><span>${i.active?'Activa':'Inactiva'} · ${esc(i.severity)}</span></button>`;if(currentTab==='reviews')return `<button class="item-row${selectedId===i.id?' active':''}" type="button" data-id="${esc(i.id)}"><strong>${esc(i.name)}${i.rating?' · '+'⭐'.repeat(i.rating):''}</strong><span>${esc((i.body||'').slice(0,60))}</span><span class="status-pill status-${esc(i.status)}">${esc(i.status)}</span></button>`;if(currentTab==='technologies')return `<button class="item-row${selectedId===i.id?' active':''}" type="button" data-id="${esc(i.id)}"><strong>${esc(i.icon||'◇')} ${esc(i.name)}</strong><span>${esc(i.category)} · ${esc(i.level)}${i.featured?' · Destacada':''}</span><span class="status-pill">${esc(i.status)}</span></button>`;const title=i.title||i.name||'Sin título',secondary=currentTab==='posts'?(i.category||'Novedad'):currentTab==='certificates'?(i.platform||'Certificado'):(i.slug||'Proyecto');return `<button class="item-row${selectedId===i.id?' active':''}" type="button" data-id="${esc(i.id)}"><strong>${esc(title)}</strong><span>${esc(secondary)}</span><span class="status-pill">${esc(i.status||'')}</span></button>`}).join('');itemsList.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>editItem(b.dataset.id)))}
  function hideForms(){Object.values(forms).forEach(f=>f?.classList.add('hidden'));editorPlaceholder.classList.remove('hidden');msg(editorMessage,'');$('customModerationEditor')?.remove()}
  function showForm(tab){Object.values(forms).forEach(f=>f?.classList.add('hidden'));editorPlaceholder.classList.add('hidden');forms[tab]?.classList.remove('hidden')}
  function custom(html){Object.values(forms).forEach(f=>f?.classList.add('hidden'));editorPlaceholder.classList.add('hidden');$('customModerationEditor')?.remove();const w=document.createElement('div');w.id='customModerationEditor';w.innerHTML=html;editorPanel.prepend(w);return w}
  newItemButton.addEventListener('click',()=>{if(currentTab==='reports'||currentTab==='community')return;if(currentTab==='banned'){const w=custom('<form class="editor-form" id="bannedForm"><div class="editor-title-row"><h3>Nueva palabra</h3></div><label>Palabra o frase<input name="term" maxlength="120" required></label><label>Acción<select name="severity"><option value="block">Bloquear automáticamente</option><option value="review">Enviar a revisión</option></select></label><button class="primary" type="submit">Guardar palabra</button></form>');w.querySelector('form').addEventListener('submit',saveBanned);return}selectedId=null;renderItems();const f=forms[currentTab];f.reset();qs(f,'id').value='';if(qs(f,'display_order'))qs(f,'display_order').value=currentItems.length+1;if(currentTab==='certificates')qs(f,'icon').value='🎓';if(currentTab==='technologies'){qs(f,'slug').value='';qs(f,'icon').value='◇';qs(f,'level').value='Intermedio';qs(f,'status').value='published';qs(f,'exercises').value='[]'}showForm(currentTab);msg(editorMessage,'Nuevo elemento. Completa los datos y guarda.')});
  function editItem(id){const i=currentItems.find(x=>x.id===id);if(!i)return;selectedId=id;renderItems();if(currentTab==='community')return editCommunity(i);if(currentTab==='reports')return editReport(i);if(currentTab==='banned')return editBanned(i);if(currentTab==='reviews')return editReview(i);if(currentTab==='comments')return editComment(i);const f=forms[currentTab];f.reset();qs(f,'id').value=i.id;if(currentTab==='posts'){['title','category','status','excerpt','content','cover_image_url','image_alt'].forEach(k=>{if(qs(f,k))qs(f,k).value=i[k]??''});f.querySelector('.image-current').textContent=i.cover_image_url?`Actual: ${i.cover_image_url}`:''}else if(currentTab==='projects'){['name','description','status','display_order','project_url','github_url','image_url','image_label'].forEach(k=>{if(qs(f,k))qs(f,k).value=i[k]??''});qs(f,'technologies').value=(i.technologies||[]).join(', ');f.querySelector('.image-current').textContent=i.image_url?`Actual: ${i.image_url}`:''}else if(currentTab==='certificates'){['title','platform','icon','description','issue_date','display_order','status','image_url','credential_url'].forEach(k=>{if(qs(f,k))qs(f,k).value=i[k]??''});qs(f,'credential_external').value=i.credential_url&&/^https?:\/\//.test(i.credential_url)?i.credential_url:'';f.querySelector('.image-current').textContent=i.image_url?`Actual: ${i.image_url}`:'';f.querySelector('.credential-current').textContent=i.credential_url?`Actual: ${i.credential_url}`:''}else if(currentTab==='technologies'){['name','slug','icon','description','category','level','display_order','status','practice_intro'].forEach(k=>{if(qs(f,k))qs(f,k).value=i[k]??''});qs(f,'featured').checked=Boolean(i.featured);qs(f,'practice_enabled').checked=Boolean(i.practice_enabled);qs(f,'exercises').value=JSON.stringify(i.exercises||[],null,2)}showForm(currentTab);msg(editorMessage,'')}
  function editCommunity(i){const w=custom(`<div class="editor-title-row"><h3>Revisión de práctica</h3><button class="danger-link" id="deleteCommunity" type="button">Eliminar</button></div><div class="review-meta"><span class="status-pill status-${esc(i.status)}">${esc(i.status)}</span><span>@${esc(i.nickname||'Usuario')}</span><span>${esc(i.technology||'')}</span></div><label>Título<input id="communityTitle" value="${esc(i.title||'')}"></label><label>Motivo de moderación<textarea id="communityReason" rows="3">${esc(i.moderation_reason||'')}</textarea></label><label>Código<textarea id="communityCode" rows="15" readonly>${esc(i.code||i.content||'')}</textarea></label><div class="moderation-actions"><button class="primary" id="approveCommunity" type="button">✓ Aprobar</button><button class="ghost danger-button" id="rejectCommunity" type="button">✕ Rechazar</button><button class="ghost" id="hideCommunity" type="button">◌ Ocultar</button></div>`);w.querySelector('#approveCommunity').addEventListener('click',()=>moderate(i,'approved'));w.querySelector('#rejectCommunity').addEventListener('click',()=>moderate(i,'rejected'));w.querySelector('#hideCommunity').addEventListener('click',()=>moderate(i,'hidden'));w.querySelector('#deleteCommunity').addEventListener('click',()=>deleteCommunity(i.id))}
  async function moderate(i,status){const reason=$('communityReason')?.value.trim()||(status==='approved'?'Aprobación manual':'Moderación manual'),payload={status,moderation_reason:reason,reviewed_by:currentUser.id,reviewed_at:new Date().toISOString(),published_at:status==='approved'?new Date().toISOString():null};const {error}=await db.from('community_posts').update(payload).eq('id',i.id);if(error)return msg(editorMessage,error.message,'error');await db.from('moderation_logs').insert({post_id:i.id,actor_id:currentUser.id,action:`manual_${status}`,reason,metadata:{}});msg(editorMessage,`Publicación ${status==='approved'?'aprobada':status==='rejected'?'rechazada':'ocultada'} correctamente.`,'success');await loadItems()}
  async function deleteCommunity(id){if(!confirm('¿Eliminar definitivamente esta publicación?'))return;const {error}=await db.from('community_posts').delete().eq('id',id);if(error)return msg(editorMessage,error.message,'error');selectedId=null;hideForms();await loadItems()}

  function editComment(i){
    const w=custom(`<div class="editor-title-row"><h3>${i.kind==='project'?'Comentario de proyecto':'Comentario de publicación'}</h3><span class="status-pill">${i.deleted_at?'RETIRADO':'ACTIVO'}</span></div><p class="review-text"><strong>Fecha:</strong> ${esc(new Date(i.created_at).toLocaleString('es-PE'))}</p><label>Comentario<textarea id="commentBodyAdmin" rows="7" readonly>${esc(i.body||'')}</textarea></label><label>Motivo de moderación<textarea id="commentModerationReason" rows="4" placeholder="Explica claramente por qué retiras este comentario.">${esc(i.moderation_reason||'')}</textarea></label>${i.deleted_at?'<p class="review-text">Este comentario ya fue retirado y la persona conserva el aviso en su perfil.</p>':'<button class="primary" id="removeCommentAdmin" type="button">🗑 Retirar comentario</button>'}`);
    w.querySelector('#removeCommentAdmin')?.addEventListener('click',()=>moderateComment(i));
  }
  async function moderateComment(i){
    const reason=$('commentModerationReason')?.value.trim();
    if(!reason||reason.length<3)return msg(editorMessage,'Escribe el motivo de moderación.','error');
    const fn=i.kind==='project'?'moderate_community_project_comment':'moderate_community_comment';
    const {data,error}=await db.rpc(fn,{p_comment_id:i.id,p_reason:reason});
    if(error)return msg(editorMessage,error.message||'No se pudo retirar el comentario.','error');
    msg(editorMessage,'Comentario retirado. El motivo quedó visible en el perfil del usuario.','success');
    try{if(data?.notification_id)await db.functions.invoke('notify-moderation',{body:{notification_id:data.notification_id}})}catch(_){/* El aviso en perfil ya quedó guardado aunque el correo no esté configurado. */}
    await loadItems();
  }
  function editReview(i){const w=custom(`<div class="editor-title-row"><h3>Reseña de ${esc(i.name)}</h3><button class="danger-link" id="deleteReview" type="button">Eliminar</button></div><div class="review-meta"><span class="status-pill status-${esc(i.status)}">${esc(i.status)}</span><span>${i.rating?'⭐'.repeat(i.rating):'Sin calificación'}</span><span>${esc(new Date(i.created_at).toLocaleString('es-PE'))}</span></div><p class="review-text">${esc(i.body)}</p><label>Motivo de moderación<textarea id="reviewReason" rows="3">${esc(i.moderation_reason||'')}</textarea></label><div class="moderation-actions"><button class="primary" id="approveReview" type="button">✓ Aprobar</button><button class="ghost danger-button" id="rejectReview" type="button">✕ Rechazar</button></div>`);w.querySelector('#approveReview').addEventListener('click',()=>moderateReview(i,'approved'));w.querySelector('#rejectReview').addEventListener('click',()=>moderateReview(i,'rejected'));w.querySelector('#deleteReview').addEventListener('click',async()=>{if(!confirm('¿Eliminar definitivamente esta reseña?'))return;const {error}=await db.from('portfolio_reviews').delete().eq('id',i.id);if(error)return msg(editorMessage,error.message,'error');selectedId=null;hideForms();await loadItems()})}
  async function moderateReview(i,status){const reason=$('reviewReason')?.value.trim()||(status==='approved'?'Aprobación manual':'Moderación manual');const {error}=await db.from('portfolio_reviews').update({status,moderation_reason:reason}).eq('id',i.id);if(error)return msg(editorMessage,error.message,'error');msg(editorMessage,`Reseña ${status==='approved'?'aprobada':'rechazada'} correctamente.`,'success');await loadItems()}
  function editReport(i){custom(`<div class="editor-title-row"><h3>Reporte</h3><span class="status-pill">${esc(i.status)}</span></div><p class="review-text"><strong>Motivo:</strong> ${esc(i.reason)}</p><p class="review-text"><strong>Detalle:</strong> ${esc(i.details||'Sin detalle')}</p><p class="review-text"><strong>Publicación:</strong> ${esc(i.community_posts?.title||'No disponible')}</p><div class="moderation-actions"><button class="primary" id="reviewReport" type="button">Marcar revisado</button><button class="ghost" id="dismissReport" type="button">Descartar</button></div>`);$('reviewReport').addEventListener('click',()=>updateReport(i,'reviewed'));$('dismissReport').addEventListener('click',()=>updateReport(i,'dismissed'))}
  async function updateReport(i,status){const {error}=await db.from('community_reports').update({status,reviewed_by:currentUser.id,reviewed_at:new Date().toISOString()}).eq('id',i.id);if(error)return msg(editorMessage,error.message,'error');await db.from('moderation_logs').insert({post_id:i.post_id,actor_id:currentUser.id,action:`report_${status}`,reason:i.reason,metadata:{report_id:i.id}});msg(editorMessage,'Reporte actualizado.','success');await loadItems()}
  function editBanned(i){const w=custom(`<div class="editor-title-row"><h3>Regla de moderación</h3><button class="danger-link" id="deleteBanned" type="button">Eliminar</button></div><label>Palabra o frase<input id="bannedTerm" maxlength="120" value="${esc(i.term)}"></label><label>Acción<select id="bannedSeverity"><option value="block" ${i.severity==='block'?'selected':''}>Bloquear automáticamente</option><option value="review" ${i.severity==='review'?'selected':''}>Enviar a revisión</option></select></label><label class="inline-check"><input id="bannedActive" type="checkbox" ${i.active?'checked':''}> Regla activa</label><button class="primary" id="saveBanned" type="button">Guardar cambios</button>`);w.querySelector('#saveBanned').addEventListener('click',async()=>{const {error}=await db.from('banned_words').update({term:w.querySelector('#bannedTerm').value.trim(),severity:w.querySelector('#bannedSeverity').value,active:w.querySelector('#bannedActive').checked}).eq('id',i.id);if(error)return msg(editorMessage,error.message,'error');msg(editorMessage,'Regla actualizada.','success');await loadItems();editBanned({...i,term:w.querySelector('#bannedTerm').value.trim(),severity:w.querySelector('#bannedSeverity').value,active:w.querySelector('#bannedActive').checked})});w.querySelector('#deleteBanned').addEventListener('click',async()=>{if(!confirm('¿Eliminar esta regla?'))return;const {error}=await db.from('banned_words').delete().eq('id',i.id);if(error)return msg(editorMessage,error.message,'error');selectedId=null;hideForms();await loadItems()})}
  async function saveBanned(e){e.preventDefault();const f=e.currentTarget,term=f.elements.term.value.trim();if(!term)return;const {error}=await db.from('banned_words').insert({term,severity:f.elements.severity.value,active:true,created_by:currentUser.id});if(error)return msg(editorMessage,error.message,'error');msg(editorMessage,'Palabra agregada.','success');await loadItems()}
  async function uploadFile(file,folder){if(!file)return'';const ext=(file.name.split('.').pop()||'bin').toLowerCase(),stem=slugify(file.name.replace(/\.[^.]+$/,'')).slice(0,60),path=`${folder}/${Date.now()}-${stem}.${ext}`;const {error}=await db.storage.from(cfg.mediaBucket).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||undefined});if(error)throw error;return db.storage.from(cfg.mediaBucket).getPublicUrl(path).data.publicUrl}
  forms.posts.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,id=qs(f,'id').value;try{msg(editorMessage,'Guardando…');let cover=qs(f,'cover_image_url').value;const file=qs(f,'cover_file').files[0];if(file)cover=await uploadFile(file,'posts');const title=qs(f,'title').value.trim(),status=qs(f,'status').value,p={title,slug:id?currentItems.find(x=>x.id===id)?.slug||slugify(title):slugify(title),category:qs(f,'category').value.trim()||'Novedad',excerpt:qs(f,'excerpt').value.trim(),content:qs(f,'content').value.trim(),cover_image_url:cover||null,image_alt:qs(f,'image_alt').value.trim()||null,status,published_at:status==='published'?(currentItems.find(x=>x.id===id)?.published_at||new Date().toISOString()):null};const r=id?await db.from('posts').update(p).eq('id',id):await db.from('posts').insert(p).select().single();if(r.error)throw r.error;msg(editorMessage,'Publicación guardada.','success');await loadItems()}catch(error){msg(editorMessage,error.message,'error')}});
  forms.projects.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,id=qs(f,'id').value;try{msg(editorMessage,'Guardando…');let image=qs(f,'image_url').value;const file=qs(f,'image_file').files[0];if(file)image=await uploadFile(file,'projects');const name=qs(f,'name').value.trim(),p={name,slug:id?currentItems.find(x=>x.id===id)?.slug||slugify(name):slugify(name),description:qs(f,'description').value.trim(),image_url:image||null,image_label:qs(f,'image_label').value.trim()||name.toUpperCase(),project_url:qs(f,'project_url').value.trim()||null,github_url:qs(f,'github_url').value.trim()||null,technologies:qs(f,'technologies').value.split(',').map(v=>v.trim()).filter(Boolean),status:qs(f,'status').value,display_order:Number(qs(f,'display_order').value||0)};const r=id?await db.from('projects').update(p).eq('id',id):await db.from('projects').insert(p).select().single();if(r.error)throw r.error;msg(editorMessage,'Proyecto guardado.','success');await loadItems()}catch(error){msg(editorMessage,error.message,'error')}});
  forms.certificates.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,id=qs(f,'id').value;try{msg(editorMessage,'Guardando…');let image=qs(f,'image_url').value,credential=qs(f,'credential_url').value;const imageFile=qs(f,'image_file').files[0],credentialFile=qs(f,'credential_file').files[0];if(imageFile)image=await uploadFile(imageFile,'certificates/images');if(credentialFile)credential=await uploadFile(credentialFile,'certificates/files');const external=qs(f,'credential_external').value.trim();if(external)credential=external;const p={title:qs(f,'title').value.trim(),platform:qs(f,'platform').value.trim()||null,icon:qs(f,'icon').value.trim()||'🎓',description:qs(f,'description').value.trim()||null,image_url:image||null,credential_url:credential||null,issue_date:qs(f,'issue_date').value||null,status:qs(f,'status').value,display_order:Number(qs(f,'display_order').value||0)};const r=id?await db.from('certificates').update(p).eq('id',id):await db.from('certificates').insert(p).select().single();if(r.error)throw r.error;msg(editorMessage,'Certificado guardado.','success');await loadItems()}catch(error){msg(editorMessage,error.message,'error')}});
  forms.technologies.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,id=qs(f,'id').value;try{msg(editorMessage,'Guardando tecnología…');let exercises=[];try{exercises=JSON.parse(qs(f,'exercises').value||'[]');if(!Array.isArray(exercises))throw new Error('Los ejercicios deben ser un arreglo JSON.')}catch(err){return msg(editorMessage,`JSON de ejercicios inválido: ${err.message}`,'error')}const name=qs(f,'name').value.trim(),slug=qs(f,'slug').value.trim()||slugify(name);if(!name)return msg(editorMessage,'El nombre es obligatorio.','error');const p={name,slug,icon:qs(f,'icon').value.trim()||'◇',description:qs(f,'description').value.trim(),category:qs(f,'category').value.trim()||'Tecnología',level:qs(f,'level').value,display_order:Number(qs(f,'display_order').value||0),featured:qs(f,'featured').checked,practice_enabled:qs(f,'practice_enabled').checked,practice_intro:qs(f,'practice_intro').value.trim()||null,exercises,status:qs(f,'status').value};const r=id?await db.from('technologies').update(p).eq('id',id):await db.from('technologies').insert(p).select().single();if(r.error)throw r.error;msg(editorMessage,'Tecnología guardada correctamente.','success');await loadItems();if(r.data?.id)editItem(r.data.id)}catch(error){msg(editorMessage,error.message,'error')}});
  document.addEventListener('click',async e=>{const b=e.target.closest('.delete-button');if(!b||b.closest('#customModerationEditor'))return;const form=b.closest('form'),id=qs(form,'id')?.value;if(!id)return;if(!confirm('¿Seguro que quieres eliminar este elemento? Esta acción no se puede deshacer.'))return;const {error}=await db.from(currentTab).delete().eq('id',id);if(error)return msg(editorMessage,error.message,'error');selectedId=null;hideForms();await loadItems()});
  initAuth();
})();
